name: Update Profile

on:
  workflow_dispatch:

  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  update-profile:
    runs-on: ubuntu-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v4

      - name: Install Python packages
        run: |
          python3 -m pip install requests Pillow

      - name: Generate portrait
        run: python3 scripts/generate_portrait.py

      - name: Generate profile
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 scripts/test.py

      - name: Save changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/portrait.svg profile.svg

          git commit -m "Update generated profile" || echo "No changes to commit"

          git push
